# Cells are sections on a page and are acting as containers for elements.
# Cells are defined here: /config/alchemy/cells.yml
# You also have to define the cells to use in your /config/alchemy/page_layouts.yml
# Please be aware: You can only add elements that are both defined in your cells.yml and page_layouts.yml!

- name: blog_column
  elements: [blog_post]

- name: left_side_bar
  elements: [categories_block]
 