# In this configuration you setup Alchemy´s element layouts.
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

# Blog Title Element
# Blog should have unique title
# Contains title and text attributes
# Essencetext - Simple Text
# Default attribute provides the preset value
- name: blog_title
  unique: true 
  contents:
  - name: title
    type: EssenceText
    default: Blog
  - name: text
    type: EssenceText
    default: This is my blog. It's awesome.

# Blog Post Element
# Contains image, date, title, author, text attributes
# The title is represented by blog_post_title
# Its just a text, so we took EssenceText as type
# Below settings we use linkable: true, because the user should be able to choose a link for the title of the blog post.
# The meta data link author and creation date corresponds to blog_post_meta
# The blog_post_intro_text & the main content blog_post_content get the type EssenceRichtext, 
# since the user likes to add multiline paragraphs.
# The blog_post_image is of type EssencePicture. This will empower the user to add an image.

- name: blog_post
  contents:
  - name: blog_post_title
    type: EssenceText
    default: Blog Post Title
    settings:
      linkable: true
  - name: blog_post_meta
    type: EssenceText
    default: "Written by John Smith on August 12, 2012"
  - name: blog_post_intro_text
    type: EssenceRichtext
  - name: blog_post_image
    type: EssencePicture
  - name: blog_post_content
    type: EssenceRichtext

# The ‘categories block’ has a headline and a list of available categories.
# The categories_headline is represented by an EssenceText. 
# In the backend the user should be able to add categories easily and dynamically. 
# Thats the reason why we choose the available_contents option.
# Its important to copy the definition of category below contents to available_contents. 
# Besides this, we also make the EssenceText deletable and linkable via settings.

- name: categories_block
  contents:
  - name: categories_headline
    type: EssenceText
    default: Categories
  - name: category
    type: EssenceText
    settings:
      deleteable: true
      linkable: true
  available_contents:
  - name: category
    type: EssenceText
    settings:
      deletable: true
      linkable: true



